import { chromium } from 'playwright';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1024},deviceScaleFactor:1});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:'validation/implementation-desktop.png'});
const assets=await page.locator('img').evaluateAll(images=>images.map(img=>({src:img.getAttribute('src'),loaded:img.complete&&img.naturalWidth>0,rect:{x:img.getBoundingClientRect().x,y:img.getBoundingClientRect().y,width:img.getBoundingClientRect().width,height:img.getBoundingClientRect().height}})));
const headings=await page.locator('h1').evaluateAll(nodes=>nodes.map(node=>({text:node.textContent,rect:node.getBoundingClientRect().toJSON(),font:getComputedStyle(node).font})));
await page.getByRole('searchbox').count().catch(()=>0);
await page.getByRole('textbox',{name:'Course, topic, creator'}).fill('design');
await page.getByRole('button',{name:'Search',exact:true}).click();
await page.waitForURL('**/?q=design');
await page.setViewportSize({width:768,height:1024});await page.screenshot({path:'validation/implementation-tablet.png'});
await page.setViewportSize({width:390,height:900});await page.screenshot({path:'validation/implementation-mobile.png'});
const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await writeFile('validation/browser-report.json',JSON.stringify({errors,assets,headings,searchWorks:page.url().includes('q=design'),mobileOverflow},null,2));
await browser.close();
if(errors.length||assets.some(asset=>!asset.loaded)||mobileOverflow)throw Error('Browser validation failed');
console.log('Desktop, tablet, mobile screenshots saved; assets loaded; search works; no page errors or mobile overflow.');
